project:
  type: website
  output-dir: docs
  
website:
  title: "swapnajak"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - STAT-515 MidTerm Project.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true