---
title: "Projects"
#author: "Swapnaja Sunil Kulkarni"
editor: visual
---

## Publications

\[1\] Rajesh J. Sharma, Swapnaja S. Kulkarni, Nikita S. Jadhav, Vaishnavi H Pisal. Assessment of Anti – fertility activity of Butea monosperma seed’s aqueous extract using Capra hircus in – vitro uterus system. International Journal of Research and Analytical Reviews, 7(1):633-636, 2020.

\[2\] Gajendra R. Shahapure, Swapnaja S. Kulkarni and Smita M. Pore. Monthly variation of physico-chemical and microbiological characteristics of Sambhaji lake in Solapur, Maharashtra. Pelagia Research Library, Ad- vances in Applied Science Research, 5(2):149-152, 2014.

## Symposiums

\[1\] ”Recombinant Products,” Exploring Microbial Biotechnology, Microbiologists Society India, Solapur, MH, January 2014.

\[2\] ”Development of Novel Formulation from Syzygium cumini As Potent Hyperglycemic Agent,” Avishkaar, Solapur, MH, India, January 2015.

## Projects

\[1\] Antifertility activity of Butea monosperma using goat uterus as model system 2015 – 2016

• Evaluated the effect of 1% aqueous seed extract of Butea monosperma in Capra hircus uterus in-vitro model system

• Concluded the anti-fertility activity of plant extract based on histology techniques and anti-fertility assay exhibiting reduced diameter of uterine glands, and altered morphology

\[2\] Assessment & analysis of physical, chemical, microbiological characteristics of fresh water in Sambhaji Lake, Solapur, Maharashtra. 2013 – 2014

• Performed water Sampling to analyze the biophysical changes and microbial contamination of Sambhaji lake, indicating decreased water quality and unhealthy for human consumption, and thus, developing a need to monitor the pollution parameters periodically
